name: CI
on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main

jobs:
  build_publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Export to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./images/xk6-coap/Dockerfile
          platforms: linux/amd64
          load: true
          tags: golioth/xk6-coap

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        if: github.ref == 'refs/heads/main'
        with:
          username: goliothbot
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push to Dockerhub
        uses: docker/build-push-action@v4
        if: github.ref == 'refs/heads/main'
        with:
          context: .
          file: ./images/xk6-coap/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: golioth/xk6-coap
